llama2-7b:
  use_mcore_models: true
  sequence_parallel: true
  num_layers: 32
  hidden_size: 4096
  ffn_hidden_size: 11008
  num_attention_heads: 32
  seq_length: 4096
  max_position_embeddings: 4096
  make_vocab_size_divisible_by: 1
  untie_embeddings_and_output_weights: true
  disable_bias_linear: true
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  position_embedding_type: rope
  normalization: RMSNorm
  use_fused_rmsnorm: true
  swiglu: true
  use_flash_attn: true
  use_mc2: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true